export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_CLEAR_STATE = "REGISTER_CLEAR_STATE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const LOG_OUT = "LOG_OUT";
